#!/usr/bin/python
#A script for dumping Skype logs
#Author: Patrick Crain

#types
#  30  = call
#  39  = also call
#  50  = sent contact request message
#  51  = ??? [first chat?]
#  60  = /me command
#  61  = normal
#  68  = sent file
#  201 = sent picture

import sqlite3, datetime, re, html, argparse, os, platform

HOME = os.path.expanduser("~")
OUTFILE=None

_lastdate=""
_title=""
_me=""
_partner=""
_outfilename=""

class col:
  BLN      ='\033[0m'            # Blank
  UND      ='\033[1;4m'          # Underlined
  INV      ='\033[1;7m'          # Inverted
  CRT      ='\033[1;41m'         # Critical
  BLK      ='\033[1;30m'         # Black
  RED      ='\033[1;31m'         # Red
  GRN      ='\033[1;32m'         # Green
  YLW      ='\033[1;33m'         # Yellow
  BLU      ='\033[1;34m'         # Blue
  MGN      ='\033[1;35m'         # Magenta
  CYN      ='\033[1;36m'         # Cyan
  WHT      ='\033[1;37m'         # White

def htmlwrite(s):
  OUTFILE.write(s+"\n")
def htmlopen():
  global OUTFILE
  OUTFILE = open(_outfilename,'w')
  htmlwrite("<!DOCTYPE html>")
  htmlwrite('<head>')
  htmlwrite('<meta charset="UTF-8">')
  htmlwrite('<link rel="stylesheet" type="text/css" href="assets/style.css">')
  htmlwrite('<script src="./assets/jquery-2.2.0.min.js"></script>')
  htmlwrite('<script type="text/javascript">')
  htmlwrite('$(document).ready(function(){')

  # htmlwrite("$('.newday').nextUntil('tr.newday').hide();")

  htmlwrite("$('tr.toggleall').click(function(){")
  htmlwrite("  $('table').hide();")
  htmlwrite("  $('.newday').nextUntil('tr.newday').toggle();")
  htmlwrite("  $('table').show();")
  htmlwrite("});")

  htmlwrite("$('tr.newday').click(function(){")
  htmlwrite("  $(this).nextUntil('tr.newday').toggle();")
  htmlwrite("});")
  htmlwrite("});")

  htmlwrite('</script>')

  htmlwrite('</head>')
  htmlwrite('<body class="document">')
def htmlclose():
  htmlwrite('</body>')
  OUTFILE.close()

def numdate(ts):
  return datetime.datetime.fromtimestamp(int(ts)).strftime('%Y-%m-%d')

def timeonly(ts):
  return datetime.datetime.fromtimestamp(int(ts)).strftime('%I:%M:%S %p')

def fulldate(ts):
  return datetime.datetime.fromtimestamp(int(ts)).strftime('%A, %B %d, %Y')

def handlenormal(m):
  # print(col.WHT + "   " + html.unescape(m[4]) + col.BLN)
  htmlwrite("<td class=\"hideable\">")
  htmlwrite(m[3])
  htmlwrite("</td>")
  htmlwrite('<td title="'+_title+'">')
  htmlwrite(m[4])

def handleme(m):
  # print(col.YLW + "   " + m[4] + col.BLN)
  htmlwrite('<td class="mecommand" colspan="2" title="'+_title+'">')
  htmlwrite(m[3] + ' ' + m[4])

def handleimage(m):
  url=re.search(r'''uri=\"(.*?)\"''',m[4]).group(1)+ "/views/imgpsh_fullsize"
  # print(col.MGN + "   " + url + col.BLN)
  htmlwrite('<td class="inlineimage" colspan="2" title="'+_title+'">')
  htmlwrite(m[3] + ' sent an image: ' + "<a href=\""+url+"\">"+url+"</a>")

def parseline(m):
  global _lastdate, _title
  if (m[0] != 61 and m[0] != 60 and m[0] != 201):
    return

  newdate = numdate(m[2])
  if _lastdate != newdate:
    htmlwrite('<tr class="newday">')
    htmlwrite('<td colspan="3">'+fulldate(m[2])+'</td>')
    htmlwrite('</tr>')
    _lastdate = newdate

  _title="From "+m[3]+" on "+fulldate(m[2])+" at "+timeonly(m[2])

  if m[1] == _me:
    color = col.GRN
    htmlwrite('<tr class="myself">')
  else:
    color = col.CYN
    htmlwrite('<tr class="other">')
  htmlwrite("<td class=\"hideable\">")
  htmlwrite(timeonly(m[2]))
  htmlwrite("</td>")

  if (m[0] == 61):
    handlenormal(m)
  if (m[0] == 60):
    handleme(m)
  if (m[0] == 201):
    handleimage(m)

  htmlwrite('</tr>')

#Configure command line arguments for the parser
def configParser():
  parser = argparse.ArgumentParser()
  # mode = parser.add_mutually_exclusive_group()
  # mode.add_argument("-c", "--clear",    help="clear the logfile",                  action="store_true")
  # parser.add_argument("--persist",      help="don't close messages until clicked", action="store_true")
  parser.add_argument("-u", "--user",    type=str,   help="your Skype username", required=True)
  parser.add_argument("-p", "--partner", type=str,   help="conversation partner's username")
  parser.add_argument("-a", "--all",                 help="dump all single user conversations", action="store_true")
  parser.add_argument("-o", "--outfile", type=str,   help="output file name")
  return parser

def dumppartner(part,cursor):
  global _partner, _outfilename
  _partner = part
  c = cursor

  user = "\'%" + _partner + "%\'"
  if not _outfilename:
    _outfilename="./_dump-"+_partner+".html"
  print("Dumping " + _partner)
  c.execute(
    "SELECT type,author,timestamp,from_dispname,body_xml \
     FROM messages \
     WHERE chatname LIKE" + user +
    "ORDER BY timestamp ASC"
  )

  htmlopen()
  htmlwrite('<table>')
  htmlwrite('<tr class="toggleall"><td colspan="3">Click here to expand / collapse all days</td></tr>')

  for m in c.fetchall():
    parseline(m)

  htmlwrite('</table>')
  htmlclose()

def main():
  global _me, _outfilename

  args = configParser().parse_args()
  _me = args.user

  OS=platform.system()
  if OS == "Linux":
    dbpath = HOME+"/.Skype/"+_me+"/main.db"
  elif OS == "Windows":
    dbpath = HOME+"/AppData/Roaming/Skype/"+_me+"/main.db"
  elif OS == "Darwin":
    dbpath = HOME+"/Library/Application Support/Skype/"+_me+"/main.db"
  else:
    print(col.RED + "Can't find path to main.db" + col.BLN)
    exit()

  conn = sqlite3.connect(dbpath)
  c = conn.cursor()

  if args.partner:
    c.execute(
      "SELECT DISTINCT author FROM messages WHERE author LIKE \'%" + args.partner + "%\' \
      AND author NOT LIKE \'" + _me + "\'; "
    )
    u = c.fetchall()[0]
    if u[0]:
      if args.outfile:
        _outfilename = args.outfile
      dumppartner(u[0],c)
  elif args.all:
    c.execute(
      "SELECT DISTINCT author FROM messages WHERE author NOT LIKE \'" + _me + "\';"
    )
    for u in c.fetchall():
      if u[0]:
        _outfilename=None
        dumppartner(u[0],c)
  else:
    print("Must specify -p <partner> or -a")
    exit()

if __name__ == "__main__":
  main()
